baseURL = 'https://kristofferlind.github.io/hugo-tale'
languageCode = 'en-us'
title = 'tale-hugo'

# Theme settings
theme = "tale-hugo"

[params]
  Author = "Some author"
  Description = "Example description"
  EnablePreviewFeatures = false
